//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.Comment1 = new HashSet<Comment>();
        }
    
        public long ID { get; set; }
        public string Body { get; set; }
        public Nullable<long> ParentID { get; set; }
        public long TaskID { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual ICollection<Comment> Comment1 { get; set; }
        public virtual Comment Comment2 { get; set; }
        public virtual User User { get; set; }
        public virtual Task Task { get; set; }
    }
}
