//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Tasks = new HashSet<Task>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public int UserTypeID { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual LKP_UserType LKP_UserType { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
